version: '3'
services:
  test-gencerts:
    container_name: gencerts
    build: ./ssl
    volumes:
       - ./certs/:/ssl/
    image: gjuljo/gencerts:v6
  test-oidc:
    container_name: oidc
    volumes:
       - ./kcloak/:/tmp/
       - ./certs/application.keystore:/opt/jboss/keycloak/standalone/configuration/application.keystore
    environment: 
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - KEYCLOAK_IMPORT=/tmp/demo_realm.json
      - DB_VENDOR=h2
    ports:
     - "8080:8080"
     - "8443:8443"
    image: jboss/keycloak:7.0.1
    depends_on:
      - test-gencerts
  test-gatek:
    container_name: gatek
    ports:
     - "8000:8000"
    image: keycloak/keycloak-gatekeeper
    command:
      - --discovery-url=https://oidc.lvh.me:8443/auth/realms/demo
      - --client-id=testclient
      - --client-secret=819f244c-4aec-4be6-9db0-cd23944b962a
      - --listen=:8000
      - --redirection-url=https://gosaml.lvh.me:8000
      - --encryption-key=AgXa7xRcoClDEUKKDSH4X0XhL5Qy3Z2j
      - --upstream-url=https://nginx:8443
      - --enable-default-deny=true
      - --skip-upstream-tls-verify=false
      - --upstream-ca=/mycerts/myca.crt
      - --secure-cookie=true
      - --skip-openid-provider-tls-verify=false
      - --enable-https-redirection=true
      - --enable-security-filter=true
      - --force-encrypted-cookie=true
      - --tls-cert=/mycerts/gatek.crt
      - --tls-private-key=/mycerts/gatek.key      
      - --verbose
    volumes:
      - ./certs/:/mycerts/
      - ./certs/myca.crt:/etc/ssl/certs/myca.crt
    depends_on:
      - test-oidc
      - test-gencerts
    external_links:
      - oidc:oidc.lvh.me
  test-nginx:
    container_name: nginx
    build: ./nginx
    ports:
     - "8081:8443"
    volumes:
    - ./certs/nginx.crt:/etc/ssl/certs/nginx.crt
    - ./certs/nginx.key:/etc/ssl/certs/nginx.key    
    links: 
    - test-apigw
    - test-gosaml
    image: gjuljo/nginxsaml:v6
    depends_on:
      - test-goapi
      - test-gosaml      
  test-gosaml:
    container_name: gosaml
    build: ./gosaml
    ports:
     - "8002:8002"
    image: gjuljo/gosaml:v6
    environment: 
      - IDP_URL=https://oidc.lvh.me:8443/auth/realms/demo/protocol/saml/descriptor
      - REDIRECT_URL=https://gosaml.lvh.me:8000
      - PORT=8002
    external_links:
      - oidc:oidc.lvh.me
  test-apigw:
    container_name: apigw
    image: kong:1.4.0-alpine
    ports:
     - "8003:8000"
     - "9999:8001"
    environment: 
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/app/kong.yaml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    volumes:
     - ./kong:/app
    depends_on:
      - test-goapi
    command:
      - kong
      - start
      - -vv
  test-goapi:
    container_name: goapi
    build: ./goapi
    ports:
     - "8001:8001"
    image: gjuljo/goapi:v6
