version: '3'
services:
  test-oidc:
    container_name: oidc
    volumes:
       - ./kcloak/:/tmp/
    environment: 
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - KEYCLOAK_IMPORT=/tmp/demo_realm.json
    ports:
     - "8080:8080"
    image: jboss/keycloak
  test-gosaml:
    container_name: gosaml
    build: ./gosaml
    ports:
     - "8000:8002"
    image: gjuljo/gosaml
    environment: 
      - IDP_URL=http://oidc:8080/auth/realms/demo/protocol/saml/descriptor
      - REDIRECT_URL=http://localhost:8000
      - PORT=8002