version: '3'
services:
  test-oidc:
    container_name: oidc
    volumes:
       - ./kcloak/:/tmp/
    environment: 
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - KEYCLOAK_IMPORT=/tmp/demo_realm.json
      - DB_VENDOR=h2
    ports:
     - "8080:8080"
    image: jboss/keycloak:7.0.1
  test-gatek:
    container_name: gatek
    build: ./kgate
    ports:
     - "8000:8000"
    image: gjuljo/gatekeeper:v5
    command:
      - --discovery-url=http://oidc.lvh.me:8080/auth/realms/demo
      - --client-id=testclient
      - --client-secret=819f244c-4aec-4be6-9db0-cd23944b962a
      - --listen=:8000
      - --redirection-url=http://gosaml.lvh.me:8000
      - --encryption-key=AgXa7xRcoClDEUKKDSH4X0XhL5Qy3Z2j
      - --upstream-url=http://nginx:8080
      - --enable-default-deny=true
      - --skip-upstream-tls-verify
      - --secure-cookie=false
      - --skip-openid-provider-tls-verify
      - --enable-https-redirection=false
      - --enable-refresh-tokens=true
      - --store-url=boltdb:////tmp/bolt
      - --cookie-domain=gosaml.lvh.me      
      - --verbose
    depends_on:
      - test-oidc
    external_links:
      - oidc:oidc.lvh.me
  test-nginx:
    container_name: nginx
    build: ./nginx
    ports:
     - "8081:8080"
    links: 
    - test-apigw
    - test-gosaml
    image: gjuljo/nginxsaml:v5
    depends_on:
      - test-goapi
      - test-gosaml      
  test-gosaml:
    container_name: gosaml
    build: ./gosaml
    ports:
     - "8002:8002"
    image: gjuljo/gosaml:v5
    environment: 
      - IDP_URL=http://oidc.lvh.me:8080/auth/realms/demo/protocol/saml/descriptor
      - REDIRECT_URL=http://gosaml.lvh.me:8000
      - PORT=8002
    external_links:
      - oidc:oidc.lvh.me
  test-apigw:
    container_name: apigw
    image: kong:1.4.0-alpine
    ports:
     - "8003:8000"
     - "9999:8001"
    environment: 
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/app/kong.yaml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    volumes:
     - ./kong:/app
    depends_on:
      - test-goapi
    command:
      - kong
      - start
      - -vv
  test-goapi:
    container_name: goapi
    build: ./goapi
    ports:
     - "8001:8001"
    image: gjuljo/goapi:v5
