version: '3'
services:
  test-oidc:
    container_name: oidc
    volumes:
       - ./kcloak/:/tmp/
    environment: 
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - KEYCLOAK_IMPORT=/tmp/demo_realm.json
      - DB_VENDOR=h2
    ports:
     - "8080:8080"
    image: jboss/keycloak:7.0.1
  test-gosaml:
    container_name: gosaml
    build: ./gosaml
    ports:
     - "8000:8002"
    image: gjuljo/gosaml:v1
    environment: 
      - IDP_URL=http://oidc.lvh.me:8080/auth/realms/demo/protocol/saml/descriptor
      - REDIRECT_URL=http://gosaml.lvh.me:8000
      - PORT=8002
    external_links:
      - oidc:oidc.lvh.me